CREATE TABLE "Output_PlayerWar" (
	"mlbId"	INTEGER NOT NULL,
	"ModelId" INTEGER NOT NULL,
	"isHitter" INTEGER NOT NULL,
	"ModelRun"	INTEGER NOT NULL,
	"year"	INTEGER NOT NULL,
	"month"	INTEGER NOT NULL,
	"war0"	REAL NOT NULL,
	"war1"	REAL NOT NULL,
	"war2"	REAL NOT NULL,
	"war3"	REAL NOT NULL,
	"war4"	REAL NOT NULL,
	"war5"	REAL NOT NULL,
	"war6"	REAL NOT NULL,
	"war" REAL NOT NULL,
	PRIMARY KEY("mlbId", "ModelId", "isHitter", "ModelRun","year","month")
);

CREATE TABLE "WarBucketAverages" (
	"isHitter" INTEGER NOT NULL,
	"war1" REAL NOT NULL,
	"war2" REAL NOT NULL,
	"war3" REAL NOT NULL,
	"war4" REAL NOT NULL,
	"war5" REAL NOT NULL,
	"war6" REAL NOT NULL,
	
	PRIMARY KEY("isHitter")
);

CREATE INDEX "idx_Output_PlayerWar" ON "Output_PlayerWar" (
	"ModelId",
	"ModelRun",
	"mlbId",
	"year",
	"month"
);

CREATE TABLE "Output_PlayerHighestLevel" (
	"mlbId"	INTEGER NOT NULL,
	"ModelId" INTEGER NOT NULL,
	"isHitter" INTEGER NOT NULL,
	"ModelRun"	INTEGER NOT NULL,
	"year"	INTEGER NOT NULL,
	"month"	INTEGER NOT NULL,
	"DSL" REAL NOT NULL,
	"CPX" REAL NOT NULL,
	"A_LOW" REAL NOT NULL,
	"A" REAL NOT NULL,
	"A_HIGH" REAL NOT NULL,
	"AA" REAL NOT NULL,
	"AAA" REAL NOT NULL,
	"MLB" REAL NOT NULL,
	PRIMARY KEY("mlbId", "ModelId", "isHitter", "ModelRun","year","month")
);

CREATE INDEX "idx_Output_PlayerHighestLevel" ON "Output_PlayerHighestLevel" (
	"ModelId",
	"ModelRun",
	"mlbId",
	"year",
	"month"
);

CREATE TABLE Output_HitterStats (
	"MlbId" INTEGER NOT NULL,
	"ModelId" INTEGER NOT NULL,
	"ModelRun" INTEGER NOT NULL,
	"Year" INTEGER NOT NULL,
	"Month" INTEGER NOT NULL,
	"LevelId" INTEGER NOT NULL,
	"Pa" REAL NOT NULL,
	"Hit1B" REAL NOT NULL,
	"Hit2B" REAL NOT NULL,
	"Hit3B" REAL NOT NULL,
	"HitHR" REAL NOT NULL,
	"BB" REAL NOT NULL,
	"HBP" REAL NOT NULL,
	"K" REAL NOT NULL, 
	"SB" REAL NOT NULL,
	"CS" REAL NOT NULL,
	"BSR" REAL NOT NULL,
	"DRAA" REAL NOT NULL,
	"ParkRunFactor" REAL NOT NULL,
	"PercC"	REAL NOT NULL,
	"Perc1B"	REAL NOT NULL,
	"Perc2B"	REAL NOT NULL,
	"Perc3B"	REAL NOT NULL,
	"PercSS"	REAL NOT NULL,
	"PercLF"	REAL NOT NULL,
	"PercCF"	REAL NOT NULL,
	"PercRF"	REAL NOT NULL,
	"PercDH"	REAL NOT NULL,
	PRIMARY KEY("MlbId", "ModelId", "ModelRun", "Year", "Month", "LevelId")
);

CREATE INDEX "idx_Output_HitterStats" ON "Output_HitterStats" (
	"ModelId",
	"ModelRun",
	"mlbId",
	"year",
	"month",
	"levelId"
);

CREATE TABLE "Output_PitcherStats" (
	"mlbId" INTEGER NOT NULL,
	"ModelId" INTEGER NOT NULL,
	"ModelRun" INTEGER NOT NULL,
	"Year" INTEGER NOT NULL,
	"Month" INTEGER NOT NULL,
	"levelId" INTEGER NOT NULL,
	"Outs_SP" REAL NOT NULL,
	"Outs_RP" REAL NOT NULL,
	"GS" REAL NOT NULL,
	"GR" REAL NOT NULL,
	"ERA" REAL NOT NULL,
	"FIP" REAL NOT NULL,
	"HR" REAL NOT NULL,
	"BB" REAL NOT NULL,
	"HBP" REAL NOT NULL,
	"K" REAL NOT NULL,
	"ParkRunFactor" REAL NOT NULL,
	"SP_Perc" REAL NOT NULL,
	"RP_Perc" REAL NOT NULL,
	PRIMARY KEY("MlbId", "ModelId", "ModelRun", "Year", "Month", "LevelId")
);

CREATE INDEX "idx_Output_PitcherStats" ON "Output_PitcherStats" (
	"ModelId",
	"ModelRun",
	"mlbId",
	"year",
	"month",
	"levelId"
);

CREATE TABLE "Output_College_Hitter" (
	"tbcId" INTEGER NOT NULL,
	"ModelId" INTEGER NOT NULL,
	"ModelRun"	INTEGER NOT NULL,
	"year"	INTEGER NOT NULL,

	-- Draft
	"draft0"	REAL NOT NULL,
	"draft1"	REAL NOT NULL,
	"draft2"	REAL NOT NULL,
	"draft3"	REAL NOT NULL,
	"draft4"	REAL NOT NULL,
	"draft5"	REAL NOT NULL,
	"draft6"	REAL NOT NULL,
	"draft" REAL NOT NULL,

	-- WAR
	"war0"	REAL NOT NULL,
	"war1"	REAL NOT NULL,
	"war2"	REAL NOT NULL,
	"war3"	REAL NOT NULL,
	"war4"	REAL NOT NULL,
	"war5"	REAL NOT NULL,
	"war6"	REAL NOT NULL,
	"war" REAL NOT NULL,

	-- OFF
	"off0"	REAL NOT NULL,
	"off1"	REAL NOT NULL,
	"off2"	REAL NOT NULL,
	"off3"	REAL NOT NULL,
	"off4"	REAL NOT NULL,
	"off5"	REAL NOT NULL,
	"off6"	REAL NOT NULL,
	"offNone" REAL NOT NULL,

	-- DEF
	"def0"	REAL NOT NULL,
	"def1"	REAL NOT NULL,
	"def2"	REAL NOT NULL,
	"def3"	REAL NOT NULL,
	"def4"	REAL NOT NULL,
	"def5"	REAL NOT NULL,
	"def6"	REAL NOT NULL,
	"defNone" REAL NOT NULL,

	-- PA
	"pa0"	REAL NOT NULL,
	"pa1"	REAL NOT NULL,
	"pa2"	REAL NOT NULL,
	"pa3"	REAL NOT NULL,
	"pa4"	REAL NOT NULL,
	"pa5"	REAL NOT NULL,
	"pa6"	REAL NOT NULL,

	-- Pro Position
	"ProbC" REAL NOT NULL,
	"Prob1B" REAL NOT NULL,
	"Prob2B" REAL NOT NULL,
	"Prob3B" REAL NOT NULL,
	"ProbSS" REAL NOT NULL,
	"ProbLF" REAL NOT NULL,
	"ProbCF" REAL NOT NULL,
	"ProbRF" REAL NOT NULL,
	"ProbDH" REAL NOT NULL,

	PRIMARY KEY("tbcId", "ModelId", "ModelRun","year")
);

CREATE INDEX "idx_Output_College_Hitter" ON "Output_College_Hitter" (
	"ModelId",
	"ModelRun",
	"tbcId",
	"year"
);

CREATE TABLE "Output_College_Pitcher" (
	"tbcId" INTEGER NOT NULL,
	"ModelId" INTEGER NOT NULL,
	"ModelRun"	INTEGER NOT NULL,
	"year"	INTEGER NOT NULL,

	-- Draft
	"draft0"	REAL NOT NULL,
	"draft1"	REAL NOT NULL,
	"draft2"	REAL NOT NULL,
	"draft3"	REAL NOT NULL,
	"draft4"	REAL NOT NULL,
	"draft5"	REAL NOT NULL,
	"draft6"	REAL NOT NULL,
	"draft" REAL NOT NULL,

	-- WAR
	"war0"	REAL NOT NULL,
	"war1"	REAL NOT NULL,
	"war2"	REAL NOT NULL,
	"war3"	REAL NOT NULL,
	"war4"	REAL NOT NULL,
	"war5"	REAL NOT NULL,
	"war6"	REAL NOT NULL,
	"war" REAL NOT NULL,

	-- Pro Position
	"ProbSP" REAL NOT NULL,
	"ProbRP" REAL NOT NULL,

	PRIMARY KEY("tbcId", "ModelId", "ModelRun","year")
);

CREATE INDEX "idx_Output_College_Pitcher" ON "Output_College_Pitcher" (
	"ModelId",
	"ModelRun",
	"tbcId",
	"year"
);

-- Training data
CREATE TABLE "Model_TrainingHistory" (
	"ModelName"	TEXT NOT NULL,
	"IsHitter"	INTEGER NOT NULL,
	"TestLoss"	REAL NOT NULL,
	"TestLossCollege" REAL NOT NULL,
	"ModelRun"	INTEGER NOT NULL,
	PRIMARY KEY("ModelName","ModelRun","IsHitter")
);

CREATE TABLE "PlayersInTrainingData" (
	"mlbId" INTEGER NOT NULL,
	"tbcId" INTEGER NOT NULL,
	"modelId" INTEGER NOT NULL,
	"modelRun" INTEGER NOT NULL,
	"isHitter" INTEGER NOT NULL,
	"isTrain" INTEGER NOT NULL,
	PRIMARY KEY ("mlbId", "tbcId", "isHitter", "modelId", "modelRun")
);

CREATE TABLE "ModelId" (
	"id" INTEGER NOT NULL,
	"modelName" TEXT NOT NULL,
	PRIMARY KEY("id")
);

--- MLB Value Predictions
CREATE TABLE "Output_HitterMlbWar" (
    "mlbId" INTEGER NOT NULL,
    "ModelId" INTEGER NOT NULL,
    "ModelRun" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    "war_Yr0_Bkt0" REAL NOT NULL,
    "war_Yr0_Bkt1" REAL NOT NULL,
    "war_Yr0_Bkt2" REAL NOT NULL,
    "war_Yr0_Bkt3" REAL NOT NULL,
    "war_Yr0_Bkt4" REAL NOT NULL,
    "war_Yr0_Bkt5" REAL NOT NULL,
    "war_Yr0_Bkt6" REAL NOT NULL,
    "war_Yr0_Bkt7" REAL NOT NULL,
    "war0" REAL NOT NULL,
    "pa_Yr0_Bkt0" REAL NOT NULL,
    "pa_Yr0_Bkt1" REAL NOT NULL,
    "pa_Yr0_Bkt2" REAL NOT NULL,
    "pa_Yr0_Bkt3" REAL NOT NULL,
    "pa_Yr0_Bkt4" REAL NOT NULL,
    "pa_Yr0_Bkt5" REAL NOT NULL,
    "pa_Yr0_Bkt6" REAL NOT NULL,
    "pa0" REAL NOT NULL,
    "war_Yr1_Bkt0" REAL NOT NULL,
    "war_Yr1_Bkt1" REAL NOT NULL,
    "war_Yr1_Bkt2" REAL NOT NULL,
    "war_Yr1_Bkt3" REAL NOT NULL,
    "war_Yr1_Bkt4" REAL NOT NULL,
    "war_Yr1_Bkt5" REAL NOT NULL,
    "war_Yr1_Bkt6" REAL NOT NULL,
    "war_Yr1_Bkt7" REAL NOT NULL,
    "war1" REAL NOT NULL,
    "pa_Yr1_Bkt0" REAL NOT NULL,
    "pa_Yr1_Bkt1" REAL NOT NULL,
    "pa_Yr1_Bkt2" REAL NOT NULL,
    "pa_Yr1_Bkt3" REAL NOT NULL,
    "pa_Yr1_Bkt4" REAL NOT NULL,
    "pa_Yr1_Bkt5" REAL NOT NULL,
    "pa_Yr1_Bkt6" REAL NOT NULL,
    "pa1" REAL NOT NULL,
    "war_Yr2_Bkt0" REAL NOT NULL,
    "war_Yr2_Bkt1" REAL NOT NULL,
    "war_Yr2_Bkt2" REAL NOT NULL,
    "war_Yr2_Bkt3" REAL NOT NULL,
    "war_Yr2_Bkt4" REAL NOT NULL,
    "war_Yr2_Bkt5" REAL NOT NULL,
    "war_Yr2_Bkt6" REAL NOT NULL,
    "war_Yr2_Bkt7" REAL NOT NULL,
    "war2" REAL NOT NULL,
    "pa_Yr2_Bkt0" REAL NOT NULL,
    "pa_Yr2_Bkt1" REAL NOT NULL,
    "pa_Yr2_Bkt2" REAL NOT NULL,
    "pa_Yr2_Bkt3" REAL NOT NULL,
    "pa_Yr2_Bkt4" REAL NOT NULL,
    "pa_Yr2_Bkt5" REAL NOT NULL,
    "pa_Yr2_Bkt6" REAL NOT NULL,
    "pa2" REAL NOT NULL,
    "war_Yr3_Bkt0" REAL NOT NULL,
    "war_Yr3_Bkt1" REAL NOT NULL,
    "war_Yr3_Bkt2" REAL NOT NULL,
    "war_Yr3_Bkt3" REAL NOT NULL,
    "war_Yr3_Bkt4" REAL NOT NULL,
    "war_Yr3_Bkt5" REAL NOT NULL,
    "war_Yr3_Bkt6" REAL NOT NULL,
    "war_Yr3_Bkt7" REAL NOT NULL,
    "war3" REAL NOT NULL,
    "pa_Yr3_Bkt0" REAL NOT NULL,
    "pa_Yr3_Bkt1" REAL NOT NULL,
    "pa_Yr3_Bkt2" REAL NOT NULL,
    "pa_Yr3_Bkt3" REAL NOT NULL,
    "pa_Yr3_Bkt4" REAL NOT NULL,
    "pa_Yr3_Bkt5" REAL NOT NULL,
    "pa_Yr3_Bkt6" REAL NOT NULL,
    "pa3" REAL NOT NULL,
    "war_Yr4_Bkt0" REAL NOT NULL,
    "war_Yr4_Bkt1" REAL NOT NULL,
    "war_Yr4_Bkt2" REAL NOT NULL,
    "war_Yr4_Bkt3" REAL NOT NULL,
    "war_Yr4_Bkt4" REAL NOT NULL,
    "war_Yr4_Bkt5" REAL NOT NULL,
    "war_Yr4_Bkt6" REAL NOT NULL,
    "war_Yr4_Bkt7" REAL NOT NULL,
    "war4" REAL NOT NULL,
    "pa_Yr4_Bkt0" REAL NOT NULL,
    "pa_Yr4_Bkt1" REAL NOT NULL,
    "pa_Yr4_Bkt2" REAL NOT NULL,
    "pa_Yr4_Bkt3" REAL NOT NULL,
    "pa_Yr4_Bkt4" REAL NOT NULL,
    "pa_Yr4_Bkt5" REAL NOT NULL,
    "pa_Yr4_Bkt6" REAL NOT NULL,
    "pa4" REAL NOT NULL,
    "war_Yr5_Bkt0" REAL NOT NULL,
    "war_Yr5_Bkt1" REAL NOT NULL,
    "war_Yr5_Bkt2" REAL NOT NULL,
    "war_Yr5_Bkt3" REAL NOT NULL,
    "war_Yr5_Bkt4" REAL NOT NULL,
    "war_Yr5_Bkt5" REAL NOT NULL,
    "war_Yr5_Bkt6" REAL NOT NULL,
    "war_Yr5_Bkt7" REAL NOT NULL,
    "war5" REAL NOT NULL,
    "pa_Yr5_Bkt0" REAL NOT NULL,
    "pa_Yr5_Bkt1" REAL NOT NULL,
    "pa_Yr5_Bkt2" REAL NOT NULL,
    "pa_Yr5_Bkt3" REAL NOT NULL,
    "pa_Yr5_Bkt4" REAL NOT NULL,
    "pa_Yr5_Bkt5" REAL NOT NULL,
    "pa_Yr5_Bkt6" REAL NOT NULL,
    "pa5" REAL NOT NULL,
    "war_Yr6_Bkt0" REAL NOT NULL,
    "war_Yr6_Bkt1" REAL NOT NULL,
    "war_Yr6_Bkt2" REAL NOT NULL,
    "war_Yr6_Bkt3" REAL NOT NULL,
    "war_Yr6_Bkt4" REAL NOT NULL,
    "war_Yr6_Bkt5" REAL NOT NULL,
    "war_Yr6_Bkt6" REAL NOT NULL,
    "war_Yr6_Bkt7" REAL NOT NULL,
    "war6" REAL NOT NULL,
    "pa_Yr6_Bkt0" REAL NOT NULL,
    "pa_Yr6_Bkt1" REAL NOT NULL,
    "pa_Yr6_Bkt2" REAL NOT NULL,
    "pa_Yr6_Bkt3" REAL NOT NULL,
    "pa_Yr6_Bkt4" REAL NOT NULL,
    "pa_Yr6_Bkt5" REAL NOT NULL,
    "pa_Yr6_Bkt6" REAL NOT NULL,
    "pa6" REAL NOT NULL,
    PRIMARY KEY("mlbId", "ModelId", "ModelRun", "year", "month")
);
CREATE TABLE "Output_PitcherMlbWar" (
    "mlbId" INTEGER NOT NULL,
    "ModelId" INTEGER NOT NULL,
    "ModelRun" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    "outsSP_Yr0_Bkt0" REAL NOT NULL,
    "outsSP_Yr0_Bkt1" REAL NOT NULL,
    "outsSP_Yr0_Bkt2" REAL NOT NULL,
    "outsSP_Yr0_Bkt3" REAL NOT NULL,
    "outsSP_Yr0_Bkt4" REAL NOT NULL,
    "outsSP_Yr0_Bkt5" REAL NOT NULL,
    "outsSP_Yr0_Bkt6" REAL NOT NULL,
    "outsSP_Yr0_Bkt7" REAL NOT NULL,
    "outsSP0" REAL NOT NULL,
    "warSP_Yr0_Bkt0" REAL NOT NULL,
    "warSP_Yr0_Bkt1" REAL NOT NULL,
    "warSP_Yr0_Bkt2" REAL NOT NULL,
    "warSP_Yr0_Bkt3" REAL NOT NULL,
    "warSP_Yr0_Bkt4" REAL NOT NULL,
    "warSP_Yr0_Bkt5" REAL NOT NULL,
    "warSP_Yr0_Bkt6" REAL NOT NULL,
    "warSP_Yr0_Bkt7" REAL NOT NULL,
    "warSP0" REAL NOT NULL,
    "outsRP_Yr0_Bkt0" REAL NOT NULL,
    "outsRP_Yr0_Bkt1" REAL NOT NULL,
    "outsRP_Yr0_Bkt2" REAL NOT NULL,
    "outsRP_Yr0_Bkt3" REAL NOT NULL,
    "outsRP_Yr0_Bkt4" REAL NOT NULL,
    "outsRP_Yr0_Bkt5" REAL NOT NULL,
    "outsRP_Yr0_Bkt6" REAL NOT NULL,
    "outsRP_Yr0_Bkt7" REAL NOT NULL,
    "outsRP0" REAL NOT NULL,
    "warRP_Yr0_Bkt0" REAL NOT NULL,
    "warRP_Yr0_Bkt1" REAL NOT NULL,
    "warRP_Yr0_Bkt2" REAL NOT NULL,
    "warRP_Yr0_Bkt3" REAL NOT NULL,
    "warRP_Yr0_Bkt4" REAL NOT NULL,
    "warRP_Yr0_Bkt5" REAL NOT NULL,
    "warRP_Yr0_Bkt6" REAL NOT NULL,
    "warRP_Yr0_Bkt7" REAL NOT NULL,
    "warRP0" REAL NOT NULL,
    "outsSP_Yr1_Bkt0" REAL NOT NULL,
    "outsSP_Yr1_Bkt1" REAL NOT NULL,
    "outsSP_Yr1_Bkt2" REAL NOT NULL,
    "outsSP_Yr1_Bkt3" REAL NOT NULL,
    "outsSP_Yr1_Bkt4" REAL NOT NULL,
    "outsSP_Yr1_Bkt5" REAL NOT NULL,
    "outsSP_Yr1_Bkt6" REAL NOT NULL,
    "outsSP_Yr1_Bkt7" REAL NOT NULL,
    "outsSP1" REAL NOT NULL,
    "warSP_Yr1_Bkt0" REAL NOT NULL,
    "warSP_Yr1_Bkt1" REAL NOT NULL,
    "warSP_Yr1_Bkt2" REAL NOT NULL,
    "warSP_Yr1_Bkt3" REAL NOT NULL,
    "warSP_Yr1_Bkt4" REAL NOT NULL,
    "warSP_Yr1_Bkt5" REAL NOT NULL,
    "warSP_Yr1_Bkt6" REAL NOT NULL,
    "warSP_Yr1_Bkt7" REAL NOT NULL,
    "warSP1" REAL NOT NULL,
    "outsRP_Yr1_Bkt0" REAL NOT NULL,
    "outsRP_Yr1_Bkt1" REAL NOT NULL,
    "outsRP_Yr1_Bkt2" REAL NOT NULL,
    "outsRP_Yr1_Bkt3" REAL NOT NULL,
    "outsRP_Yr1_Bkt4" REAL NOT NULL,
    "outsRP_Yr1_Bkt5" REAL NOT NULL,
    "outsRP_Yr1_Bkt6" REAL NOT NULL,
    "outsRP_Yr1_Bkt7" REAL NOT NULL,
    "outsRP1" REAL NOT NULL,
    "warRP_Yr1_Bkt0" REAL NOT NULL,
    "warRP_Yr1_Bkt1" REAL NOT NULL,
    "warRP_Yr1_Bkt2" REAL NOT NULL,
    "warRP_Yr1_Bkt3" REAL NOT NULL,
    "warRP_Yr1_Bkt4" REAL NOT NULL,
    "warRP_Yr1_Bkt5" REAL NOT NULL,
    "warRP_Yr1_Bkt6" REAL NOT NULL,
    "warRP_Yr1_Bkt7" REAL NOT NULL,
    "warRP1" REAL NOT NULL,
    "outsSP_Yr2_Bkt0" REAL NOT NULL,
    "outsSP_Yr2_Bkt1" REAL NOT NULL,
    "outsSP_Yr2_Bkt2" REAL NOT NULL,
    "outsSP_Yr2_Bkt3" REAL NOT NULL,
    "outsSP_Yr2_Bkt4" REAL NOT NULL,
    "outsSP_Yr2_Bkt5" REAL NOT NULL,
    "outsSP_Yr2_Bkt6" REAL NOT NULL,
    "outsSP_Yr2_Bkt7" REAL NOT NULL,
    "outsSP2" REAL NOT NULL,
    "warSP_Yr2_Bkt0" REAL NOT NULL,
    "warSP_Yr2_Bkt1" REAL NOT NULL,
    "warSP_Yr2_Bkt2" REAL NOT NULL,
    "warSP_Yr2_Bkt3" REAL NOT NULL,
    "warSP_Yr2_Bkt4" REAL NOT NULL,
    "warSP_Yr2_Bkt5" REAL NOT NULL,
    "warSP_Yr2_Bkt6" REAL NOT NULL,
    "warSP_Yr2_Bkt7" REAL NOT NULL,
    "warSP2" REAL NOT NULL,
    "outsRP_Yr2_Bkt0" REAL NOT NULL,
    "outsRP_Yr2_Bkt1" REAL NOT NULL,
    "outsRP_Yr2_Bkt2" REAL NOT NULL,
    "outsRP_Yr2_Bkt3" REAL NOT NULL,
    "outsRP_Yr2_Bkt4" REAL NOT NULL,
    "outsRP_Yr2_Bkt5" REAL NOT NULL,
    "outsRP_Yr2_Bkt6" REAL NOT NULL,
    "outsRP_Yr2_Bkt7" REAL NOT NULL,
    "outsRP2" REAL NOT NULL,
    "warRP_Yr2_Bkt0" REAL NOT NULL,
    "warRP_Yr2_Bkt1" REAL NOT NULL,
    "warRP_Yr2_Bkt2" REAL NOT NULL,
    "warRP_Yr2_Bkt3" REAL NOT NULL,
    "warRP_Yr2_Bkt4" REAL NOT NULL,
    "warRP_Yr2_Bkt5" REAL NOT NULL,
    "warRP_Yr2_Bkt6" REAL NOT NULL,
    "warRP_Yr2_Bkt7" REAL NOT NULL,
    "warRP2" REAL NOT NULL,
    "outsSP_Yr3_Bkt0" REAL NOT NULL,
    "outsSP_Yr3_Bkt1" REAL NOT NULL,
    "outsSP_Yr3_Bkt2" REAL NOT NULL,
    "outsSP_Yr3_Bkt3" REAL NOT NULL,
    "outsSP_Yr3_Bkt4" REAL NOT NULL,
    "outsSP_Yr3_Bkt5" REAL NOT NULL,
    "outsSP_Yr3_Bkt6" REAL NOT NULL,
    "outsSP_Yr3_Bkt7" REAL NOT NULL,
    "outsSP3" REAL NOT NULL,
    "warSP_Yr3_Bkt0" REAL NOT NULL,
    "warSP_Yr3_Bkt1" REAL NOT NULL,
    "warSP_Yr3_Bkt2" REAL NOT NULL,
    "warSP_Yr3_Bkt3" REAL NOT NULL,
    "warSP_Yr3_Bkt4" REAL NOT NULL,
    "warSP_Yr3_Bkt5" REAL NOT NULL,
    "warSP_Yr3_Bkt6" REAL NOT NULL,
    "warSP_Yr3_Bkt7" REAL NOT NULL,
    "warSP3" REAL NOT NULL,
    "outsRP_Yr3_Bkt0" REAL NOT NULL,
    "outsRP_Yr3_Bkt1" REAL NOT NULL,
    "outsRP_Yr3_Bkt2" REAL NOT NULL,
    "outsRP_Yr3_Bkt3" REAL NOT NULL,
    "outsRP_Yr3_Bkt4" REAL NOT NULL,
    "outsRP_Yr3_Bkt5" REAL NOT NULL,
    "outsRP_Yr3_Bkt6" REAL NOT NULL,
    "outsRP_Yr3_Bkt7" REAL NOT NULL,
    "outsRP3" REAL NOT NULL,
    "warRP_Yr3_Bkt0" REAL NOT NULL,
    "warRP_Yr3_Bkt1" REAL NOT NULL,
    "warRP_Yr3_Bkt2" REAL NOT NULL,
    "warRP_Yr3_Bkt3" REAL NOT NULL,
    "warRP_Yr3_Bkt4" REAL NOT NULL,
    "warRP_Yr3_Bkt5" REAL NOT NULL,
    "warRP_Yr3_Bkt6" REAL NOT NULL,
    "warRP_Yr3_Bkt7" REAL NOT NULL,
    "warRP3" REAL NOT NULL,
    "outsSP_Yr4_Bkt0" REAL NOT NULL,
    "outsSP_Yr4_Bkt1" REAL NOT NULL,
    "outsSP_Yr4_Bkt2" REAL NOT NULL,
    "outsSP_Yr4_Bkt3" REAL NOT NULL,
    "outsSP_Yr4_Bkt4" REAL NOT NULL,
    "outsSP_Yr4_Bkt5" REAL NOT NULL,
    "outsSP_Yr4_Bkt6" REAL NOT NULL,
    "outsSP_Yr4_Bkt7" REAL NOT NULL,
    "outsSP4" REAL NOT NULL,
    "warSP_Yr4_Bkt0" REAL NOT NULL,
    "warSP_Yr4_Bkt1" REAL NOT NULL,
    "warSP_Yr4_Bkt2" REAL NOT NULL,
    "warSP_Yr4_Bkt3" REAL NOT NULL,
    "warSP_Yr4_Bkt4" REAL NOT NULL,
    "warSP_Yr4_Bkt5" REAL NOT NULL,
    "warSP_Yr4_Bkt6" REAL NOT NULL,
    "warSP_Yr4_Bkt7" REAL NOT NULL,
    "warSP4" REAL NOT NULL,
    "outsRP_Yr4_Bkt0" REAL NOT NULL,
    "outsRP_Yr4_Bkt1" REAL NOT NULL,
    "outsRP_Yr4_Bkt2" REAL NOT NULL,
    "outsRP_Yr4_Bkt3" REAL NOT NULL,
    "outsRP_Yr4_Bkt4" REAL NOT NULL,
    "outsRP_Yr4_Bkt5" REAL NOT NULL,
    "outsRP_Yr4_Bkt6" REAL NOT NULL,
    "outsRP_Yr4_Bkt7" REAL NOT NULL,
    "outsRP4" REAL NOT NULL,
    "warRP_Yr4_Bkt0" REAL NOT NULL,
    "warRP_Yr4_Bkt1" REAL NOT NULL,
    "warRP_Yr4_Bkt2" REAL NOT NULL,
    "warRP_Yr4_Bkt3" REAL NOT NULL,
    "warRP_Yr4_Bkt4" REAL NOT NULL,
    "warRP_Yr4_Bkt5" REAL NOT NULL,
    "warRP_Yr4_Bkt6" REAL NOT NULL,
    "warRP_Yr4_Bkt7" REAL NOT NULL,
    "warRP4" REAL NOT NULL,
    "outsSP_Yr5_Bkt0" REAL NOT NULL,
    "outsSP_Yr5_Bkt1" REAL NOT NULL,
    "outsSP_Yr5_Bkt2" REAL NOT NULL,
    "outsSP_Yr5_Bkt3" REAL NOT NULL,
    "outsSP_Yr5_Bkt4" REAL NOT NULL,
    "outsSP_Yr5_Bkt5" REAL NOT NULL,
    "outsSP_Yr5_Bkt6" REAL NOT NULL,
    "outsSP_Yr5_Bkt7" REAL NOT NULL,
    "outsSP5" REAL NOT NULL,
    "warSP_Yr5_Bkt0" REAL NOT NULL,
    "warSP_Yr5_Bkt1" REAL NOT NULL,
    "warSP_Yr5_Bkt2" REAL NOT NULL,
    "warSP_Yr5_Bkt3" REAL NOT NULL,
    "warSP_Yr5_Bkt4" REAL NOT NULL,
    "warSP_Yr5_Bkt5" REAL NOT NULL,
    "warSP_Yr5_Bkt6" REAL NOT NULL,
    "warSP_Yr5_Bkt7" REAL NOT NULL,
    "warSP5" REAL NOT NULL,
    "outsRP_Yr5_Bkt0" REAL NOT NULL,
    "outsRP_Yr5_Bkt1" REAL NOT NULL,
    "outsRP_Yr5_Bkt2" REAL NOT NULL,
    "outsRP_Yr5_Bkt3" REAL NOT NULL,
    "outsRP_Yr5_Bkt4" REAL NOT NULL,
    "outsRP_Yr5_Bkt5" REAL NOT NULL,
    "outsRP_Yr5_Bkt6" REAL NOT NULL,
    "outsRP_Yr5_Bkt7" REAL NOT NULL,
    "outsRP5" REAL NOT NULL,
    "warRP_Yr5_Bkt0" REAL NOT NULL,
    "warRP_Yr5_Bkt1" REAL NOT NULL,
    "warRP_Yr5_Bkt2" REAL NOT NULL,
    "warRP_Yr5_Bkt3" REAL NOT NULL,
    "warRP_Yr5_Bkt4" REAL NOT NULL,
    "warRP_Yr5_Bkt5" REAL NOT NULL,
    "warRP_Yr5_Bkt6" REAL NOT NULL,
    "warRP_Yr5_Bkt7" REAL NOT NULL,
    "warRP5" REAL NOT NULL,
    "outsSP_Yr6_Bkt0" REAL NOT NULL,
    "outsSP_Yr6_Bkt1" REAL NOT NULL,
    "outsSP_Yr6_Bkt2" REAL NOT NULL,
    "outsSP_Yr6_Bkt3" REAL NOT NULL,
    "outsSP_Yr6_Bkt4" REAL NOT NULL,
    "outsSP_Yr6_Bkt5" REAL NOT NULL,
    "outsSP_Yr6_Bkt6" REAL NOT NULL,
    "outsSP_Yr6_Bkt7" REAL NOT NULL,
    "outsSP6" REAL NOT NULL,
    "warSP_Yr6_Bkt0" REAL NOT NULL,
    "warSP_Yr6_Bkt1" REAL NOT NULL,
    "warSP_Yr6_Bkt2" REAL NOT NULL,
    "warSP_Yr6_Bkt3" REAL NOT NULL,
    "warSP_Yr6_Bkt4" REAL NOT NULL,
    "warSP_Yr6_Bkt5" REAL NOT NULL,
    "warSP_Yr6_Bkt6" REAL NOT NULL,
    "warSP_Yr6_Bkt7" REAL NOT NULL,
    "warSP6" REAL NOT NULL,
    "outsRP_Yr6_Bkt0" REAL NOT NULL,
    "outsRP_Yr6_Bkt1" REAL NOT NULL,
    "outsRP_Yr6_Bkt2" REAL NOT NULL,
    "outsRP_Yr6_Bkt3" REAL NOT NULL,
    "outsRP_Yr6_Bkt4" REAL NOT NULL,
    "outsRP_Yr6_Bkt5" REAL NOT NULL,
    "outsRP_Yr6_Bkt6" REAL NOT NULL,
    "outsRP_Yr6_Bkt7" REAL NOT NULL,
    "outsRP6" REAL NOT NULL,
    "warRP_Yr6_Bkt0" REAL NOT NULL,
    "warRP_Yr6_Bkt1" REAL NOT NULL,
    "warRP_Yr6_Bkt2" REAL NOT NULL,
    "warRP_Yr6_Bkt3" REAL NOT NULL,
    "warRP_Yr6_Bkt4" REAL NOT NULL,
    "warRP_Yr6_Bkt5" REAL NOT NULL,
    "warRP_Yr6_Bkt6" REAL NOT NULL,
    "warRP_Yr6_Bkt7" REAL NOT NULL,
    "warRP6" REAL NOT NULL,
    PRIMARY KEY("mlbId", "ModelId", "ModelRun", "year", "month")
);
CREATE TABLE "SingleYearHitterBucketAverages" (
    "Month" INTEGER NOT NULL,
    "war0" REAL NOT NULL,
    "war1" REAL NOT NULL,
    "war2" REAL NOT NULL,
    "war3" REAL NOT NULL,
    "war4" REAL NOT NULL,
    "war5" REAL NOT NULL,
    "war6" REAL NOT NULL,
    "war7" REAL NOT NULL,
    "pa0" REAL NOT NULL,
    "pa1" REAL NOT NULL,
    "pa2" REAL NOT NULL,
    "pa3" REAL NOT NULL,
    "pa4" REAL NOT NULL,
    "pa5" REAL NOT NULL,
    "pa6" REAL NOT NULL,
    PRIMARY KEY("Month")
);
CREATE TABLE "SingleYearPitcherBucketAverages" (
    "Month" INTEGER NOT NULL,
    "outsSP0" REAL NOT NULL,
    "outsSP1" REAL NOT NULL,
    "outsSP2" REAL NOT NULL,
    "outsSP3" REAL NOT NULL,
    "outsSP4" REAL NOT NULL,
    "outsSP5" REAL NOT NULL,
    "outsSP6" REAL NOT NULL,
    "outsSP7" REAL NOT NULL,
    "warSP0" REAL NOT NULL,
    "warSP1" REAL NOT NULL,
    "warSP2" REAL NOT NULL,
    "warSP3" REAL NOT NULL,
    "warSP4" REAL NOT NULL,
    "warSP5" REAL NOT NULL,
    "warSP6" REAL NOT NULL,
    "warSP7" REAL NOT NULL,
    "outsRP0" REAL NOT NULL,
    "outsRP1" REAL NOT NULL,
    "outsRP2" REAL NOT NULL,
    "outsRP3" REAL NOT NULL,
    "outsRP4" REAL NOT NULL,
    "outsRP5" REAL NOT NULL,
    "outsRP6" REAL NOT NULL,
    "outsRP7" REAL NOT NULL,
    "warRP0" REAL NOT NULL,
    "warRP1" REAL NOT NULL,
    "warRP2" REAL NOT NULL,
    "warRP3" REAL NOT NULL,
    "warRP4" REAL NOT NULL,
    "warRP5" REAL NOT NULL,
    "warRP6" REAL NOT NULL,
    "warRP7" REAL NOT NULL,
    PRIMARY KEY("Month")
);